# Generated by Django 5.2.4 on 2026-02-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campus name', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Campus location/address', max_length=200)),
                ('contact_number', models.CharField(blank=True, help_text='Campus contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Head_of_campus', models.ForeignKey(blank=True, help_text='Head of this campus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_head', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['partner__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School/Department name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the school/department', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Dean', models.ForeignKey(blank=True, help_text='Dean of this school/department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_dean', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(help_text='Campus this school/department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='partern.campus')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['campus__partner__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the department', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Head_of_department', models.ForeignKey(blank=True, help_text='Head of this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='partern.schools')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['school__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner organization name', max_length=100)),
                ('pattern_type', models.CharField(choices=[('institution', 'Institution'), ('corporate', 'Corporate'), ('individual', 'Individual'), ('government', 'Government')], max_length=20)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('is_approved_by_RDB', models.BooleanField(default=True, help_text='Approved by RDB')),
                ('start_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False, help_text='Partner is active and approved')),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of students allowed')),
                ('structure_type', models.CharField(choices=[('None', 'None'), ('Departmental', 'Departmental only'), ('Unversity', 'University wide')], default='None', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Partner admin who manages this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partners', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Super admin who created this partner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Partner',
                'verbose_name_plural': 'Tenant Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='partner',
            field=models.ForeignKey(help_text='Partner organization this campus belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='partern.tenantpartner'),
        ),
    ]
