# Generated by Django 5.2.4 on 2026-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpartner',
            name='allow_public_registration',
            field=models.BooleanField(default=False, help_text='Allow students to register publicly without invitation'),
        ),
    ]
