# Generated by Django 5.2.4 on 2026-02-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        ('partern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner organization this instructor belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='partern.tenantpartner'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='learners', to='courses.course'),
        ),
        migrations.AddField(
            model_name='learner',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner organization this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='partern.tenantpartner'),
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.learner'),
        ),
    ]
