# Generated by Django 5.2.4 on 2026-02-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
