# Generated by Django 5.2.4 on 2026-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20),
        ),
    ]
