# Generated by Django 5.2.4 on 2026-02-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizes',
            options={'ordering': ['order'], 'verbose_name': 'Quiz/Exam', 'verbose_name_plural': 'Quizzes & Exams'},
        ),
        migrations.AddField(
            model_name='quizes',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='description',
            field=models.TextField(blank=True, help_text='Instructions for the quiz/exam'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.module'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='title',
            field=models.CharField(default='Quiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='question',
            field=models.TextField(default='Quiz Description', help_text='Introduction/Description of the quiz'),
        ),
    ]
