# Generated by Django 5.2.4 on 2026-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_quizes_options_quizes_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If checked, this quiz/exam cannot be taken by students.'),
        ),
    ]
